name: Security Smoke Tests

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start stack
        run: docker compose up -d --build
      - name: Wait for API
        run: |
          for i in {1..60}; do curl -fsS http://localhost:4000/health && exit 0; sleep 5; done; exit 1
      - name: Run security smoke
        run: bash scripts/security-smoke.sh

