name: Container Image Scan (Trivy)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build API image
        run: docker build -t app-api:ci ./api
      - name: Build Web image
        run: docker build -t app-web:ci ./web
      - name: Scan API image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: app-api:ci
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
      - name: Scan Web image with Trivy
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: app-web:ci
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'

