name: ZAP Baseline Scan

on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 5 * * *'

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start stack
        run: docker compose up -d --build
      - name: Wait for services
        run: |
          for i in {1..60}; do curl -fsS http://localhost:4000/health && exit 0; sleep 5; done; exit 1
      - name: ZAP baseline scan API
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:4000'
          rules_file_name: '.zap/rules-api.tsv'
          cmd_options: '-a'
      - name: ZAP baseline scan Web
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'http://localhost:3000'
          rules_file_name: '.zap/rules-web.tsv'
          cmd_options: '-a'

